import { MainLayout } from "@/components/Layout";
import type { NextPage } from "next";
import Head from "next/head";
import { HrSearch } from "./HrSearch/HrSearch";

export default function Page() {
  return (
    <div>
      <Head>
        <title>Candidate</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <HrSearch />
      </main>
    </div>
  );
}
Page.getLayout = function getLayout(page: any) {
  return <MainLayout>{page}</MainLayout>;
};
